# docker-compose.yml
version: '3'

services:
  # FRRouting Container
  frr:
    image: frrouting/frr:latest
    container_name: frr-router
    privileged: true
    network_mode: "host"
    volumes:
      - ./frr/frr.conf:/etc/frr/frr.conf
      - ./frr/daemons:/etc/frr/daemons
    restart: unless-stopped

  # IPTables Firewall Container
  iptables:
    build:
      context: ./firewall
      dockerfile: Dockerfile
    container_name: iptables-fw
    privileged: true
    network_mode: "host"
    volumes:
      - ./firewall/rules.sh:/rules.sh
    restart: unless-stopped

  # StrongSwan VPN Container
  vpn:
    image: strongswan:latest
    container_name: strongswan-vpn
    privileged: true
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./vpn/ipsec.conf:/etc/ipsec.conf
      - ./vpn/ipsec.secrets:/etc/ipsec.secrets
    restart: unless-stopped

  # DHCP & DNS Container using dnsmasq
  dnsmasq:
    build:
      context: ./dnsmasq
      dockerfile: Dockerfile
    container_name: dnsmasq-server
    network_mode: "host"
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq/hosts:/etc/hosts
    cap_add:
      - NET_ADMIN
    restart: unless-stopped